services:
  app:
    container_name: app
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app_test:
    container_name: app_test
    image: maven:3.8.4-openjdk-17-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=jdbc:postgresql://task_db:5432/inventory_db
    depends_on:
      - db
    command: mvn test
